name: vin_ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  sizer2: ^2.0.16
  sizer_pro: ^2.0.19
  shared_preferences: ^2.1.2
  image_picker: ^0.8.4+4
  file_picker: ^4.0.0
  flutter_rating_bar: ^4.0.0
  firebase_storage: 
  firebase_core:

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  riverpod_lint: ^1.3.2
  http: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Text/SFProText-Black.otf
        - asset: assets/fonts/SF-Text/SFProText-BlackItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Bold.otf
        - asset: assets/fonts/SF-Text/SFProText-BoldItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Heavy.otf
        - asset: assets/fonts/SF-Text/SFProText-HeavyItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Light.otf
        - asset: assets/fonts/SF-Text/SFProText-LightItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Medium.otf
        - asset: assets/fonts/SF-Text/SFProText-MediumItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Regular.otf
        - asset: assets/fonts/SF-Text/SFProText-RegularItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Semibold.otf
        - asset: assets/fonts/SF-Text/SFProText-SemiboldItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Thin.otf
        - asset: assets/fonts/SF-Text/SFProText-ThinItalic.otf
        - asset: assets/fonts/SF-Text/SFProText-Ultralight.otf
        - asset: assets/fonts/SF-Text/SFProText-UltralightItalic.otf
