// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTCq_JhYRWDQ9Ftaubrmzf2zRYHFnC3c',
    appId: '1:239947443318:android:3b0097a1b86fa043d0c357',
    messagingSenderId: '239947443318',
    projectId: 'storestaff-vinecom',
    databaseURL: 'https://storestaff-vinecom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storestaff-vinecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxVZCRoPlQtQgAPcyXn5RoGy-Q448VKGk',
    appId: '1:239947443318:ios:2d2e798677ce205ad0c357',
    messagingSenderId: '239947443318',
    projectId: 'storestaff-vinecom',
    databaseURL: 'https://storestaff-vinecom-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storestaff-vinecom.appspot.com',
    iosClientId: '239947443318-dc9ua8l4f3fj79lqmql2eidgig8n8rbm.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.vinEcommerce',
  );
}
